name: checkov

on:
  push:
    branches:
      - master

jobs:
  Run-Checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Checkov
        uses: checkov/checkov@v1
        with:
          path: /github-actions-with-checkov
          report_file: checkov.report.json
          report_type: json