name: checkov

on:
  push:
    branches:
      - main

jobs:
  Run-Checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /github-actions-with-checkov
    steps:
      - uses: actions/checkout@v2
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          path: /github-actions-with-checkov
          report_file: checkov.report.json
          report_type: json